Repository MGMCN/pppixiv, pull requests merged in 2023-05, with the labels that each got.

#63 move load_dotenv to main.py
  Dockerfile
  app.py
  main.py
  run.sh
Labels: enhancement

#64 add config.py
  app.py
  config.py
  main.py
Labels: enhancement

#65 remove random rename function
  router/pixiv_router.py
  services/parser/illust.py
  services/pixiv.py
  static/js/index.js
Labels: enhancement

#66 Remove unnecessary code/readme about gfw mode.
  Dockerfile
  README.md
  app.py
  config.py
  run.sh
  services/pixiv.py
Labels: bug

#69 Remove duplicate download links
  services/pixiv.py
  static/js/index.js
Labels: bug, enhancement
