Repository MGMCN/pppixiv, pull requests merged in 2023-04, with the labels that each got.

#10 Token Refresher
  app.py
  services/pixiv.py
Labels: bug

#14 Retrieve illustration ranking & trending tags (preliminary ver.)
  README.md
  app.py
  services/pixiv.py
  test.py
Labels: enhancement

#18 update Dockerfile and run.sh
  Dockerfile
  run.sh
Labels: enhancement

#19 optimize dockerfile to reduce docker image size...
  Dockerfile
  run.sh
Labels: enhancement

#22 code optimized and remove some unnecessary downloaded libs & add logger & create base.py & add router directory & refactoring app.py
  app.py
  main.py
  requirements.txt
  router/pixiv_router.py
  run.sh
  services/base.py
  services/pixiv.py
Labels: enhancement

#24 README.md updated
  README.md
Labels: documentation

#26 Ending gracefully when the program goes wrong & add test cases
  main.py
  services/pixiv.py
  test.py
Labels: enhancement

#28 Unify the key-value format of returned json data
  README.md
  services/pixiv.py
Labels: enhancement

#29 update README.md
  README.md
Labels: documentation

#30 code optimized!
  app.py
  main.py
  services/base.py
Labels: enhancement

#31 Update LICENSE
  LICENSE
Labels: documentation

#34 bug fixed
  static/js/index.js
Labels: bug

#35 add image folder & success color modified & update README.md
  README.md
  image/download.jpg
  image/search.jpg
  static/css/mystyle.css
Labels: enhancement

#36 Update README.md
  README.md
Labels: documentation

#37 run.sh modified
  run.sh
Labels: bug

#38 reformat js css html
  static/css/mystyle.css
  static/js/index.js
  templates/html/index.html
Labels: enhancement

#39 bug fixed
  static/js/index.js
Labels: bug

#40 set overflow-y scroll
  static/css/mystyle.css
Labels: enhancement

#41 Update mystyle.css
  static/css/mystyle.css
Labels: enhancement

#42 Add parser
  services/base.py
  services/parser/base.py
  services/parser/illust.py
  services/parser/parser_factory.py
  services/parser/tag.py
  services/pixiv.py
Labels: enhancement

#44 bug fixed
  services/pixiv.py
Labels: bug

#45 update README.md
  .gitignore
  README.md
Labels: documentation

#46 update README.md
  README.md
Labels: documentation

#47 Reduce docker image size
  Dockerfile
Labels: enhancement

#48 code optimized
  services/parser/parser_factory.py
  services/pixiv.py
  static/js/index.js
Labels: enhancement

#49 add shortcut icon
  templates/html/index.html
Labels: enhancement

#50 add ranking-mode type
  static/css/mystyle.css
  static/js/index.js
  templates/html/index.html
Labels: enhancement

#51 add previewing downloaded illusts mode
  main.py
  services/pixiv.py
  static/css/mystyle.css
  static/js/index.js
  templates/html/index.html
Labels: enhancement

#52 index.js modified
  static/js/index.js
Labels: enhancement

#53 index.js index.html modified
  static/js/index.js
  templates/html/index.html
Labels: enhancement

#55 add gfw pixivAPI & bug fixed
  Dockerfile
  README.md
  app.py
  run.sh
  services/pixiv.py
Labels: enhancement

#57 Update README.md
  README.md
Labels: documentation

#58 Update index.js
  static/js/index.js
Labels: bug

#60 Create .dockerignore
  .dockerignore
Labels: enhancement

#61 css bug fixed
  static/css/mystyle.css
  static/js/index.js
  templates/html/index.html
Labels: bug

#62 add leftdiv.css rightdiv.css
  static/css/leftdiv.css
  static/css/main.css
  static/css/rightdiv.css
  templates/html/index.html
Labels: enhancement
